export const CHANGE_VISIBLE_BODYTYPE = 'CHANGE_VISIBLE_BODYTYPE';
export const SELECT_PART = 'SELECT_PART';
export const UPDATE_PART_LIST = 'UPDATE_PART_LIST';
export const FORM_VISIBLE = 'FORM_VISIBLE';
export const EDIT = 'EDIT';
export const CART_TOTAL = 'CART_TOTAL';
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_TIME = 'UPDATE_TIME';